services:
  postgres:
    image: postgres:15
    container_name: taskmanager-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5433:5432"
    volumes:
      - taskmanager_pgdata:/var/lib/postgresql/data

volumes:
  taskmanager_pgdata:
